### ISSUE TITLE
Image rendering issue: Module 1

### ISSUE THREAD

**Issue by srushti-714** [MicrosoftLearning/DP-203-Data-Engineer#10] opened 2021-08-06 18:30 UTC
# Module: 01 LAB_01_compute_and_storage_options.md
#### Step: 06

Description of issue
Images are not rendering properly.

Repro steps:

![image](https://user-images.githubusercontent.com/55180169/128556094-82869d3b-28c7-4da2-8b47-6b260feeb092.png)

**Comment by ctesta-oneillmsft** [comment] 2021-08-09 12:31
All the images are rendering in Github. If this is an issue with a Lab hoster, then this needs to be raised with the lab hoster

Closing as unable to reproduce in the Github repo

**Closed by ctesta-oneillmsft** 2021-08-09 12:31 UTC
