### ISSUE TITLE
Lab 2 - Minor UI update on ACL page

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-203-Data-Engineer#65] opened 2021-11-23 16:48 UTC
Regarding Exercise 2, Task 4, Step 2. The Manage Access UI has changed, so the instructions text and screenshot are in need of an update. The button is now called Add Principal.

**Comment by ctesta-oneillmsft** [comment] 2021-11-29 12:10
This issue is a duplicate of issue #60 , closing as a duplicate

**Closed by ctesta-oneillmsft** 2021-11-29 12:10 UTC

**Comment by VitalyMCT** [comment] 2021-11-29 12:27
No. The two issues are clearly for different Tasks numbers within the Exercise. 

@GraemeMalcolm  #pleasereopen

**Comment by ctesta-oneillmsft** [comment] 2021-11-29 12:28
The who of Exercise 2 is currently being updated Vitaly.
